version: '3'
services:
  spring-app:
    build:
      context: /app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tree_db
      MYSQL_USER:
      MYSQL_PASSWORD: your-database-password
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
